projeto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('receitas.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

receitas/urls.py
from django.urls import path
from . import views

app_name = 'receita'


urlpatterns = [
    path('', views.home, name='home'),
    path('receitas/categoria/<int:id_cat>/', views.categoria, name='categoria'),
    path('receitas/<int:id>/', views.receita, name='detalhe'),
]

receitas/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Categoria(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self) -> str:
        return self.name


class Receita(models.Model):
    titulo = models.CharField(max_length=65)
    descricao = models.CharField(max_length=165)
    slug = models.SlugField()
    tempo_prep = models.IntegerField()
    unidade_tempo = models.CharField(max_length=10)
    porcoes = models.IntegerField()
    unidade_porcao = models.CharField(max_length=10)
    modo_preparo = models.TextField()
    modo_preparo_is_html = models.BooleanField(default=False)
    criacao = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    is_publicado = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='receita/covers/%Y/%m/%d/', blank=True, default='')
    categoria = models.ForeignKey(
        Categoria, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return self.titulo

receitas/views.py
from django.http import Http404
from django.shortcuts import render, get_list_or_404, get_object_or_404
from utils.receitas.factore import *

from .models import Receita


def home(request):
    receita = Receita.objects.filter(is_publicado=True).order_by('-id')
    return render(request, 'receita/pages/home.html', context={
        'receitas': receita
    })


def categoria(request, id_cat):
    receita = get_list_or_404(
        Receita.objects.filter(
            categoria__id=id_cat,
            is_publicado=True).order_by('-id')
    )

    return render(request, 'receita/pages/categoria.html', context={
        'receitas': receita,
        'titulo': f'{receita[0].categoria.name}',
        })


def receita(request, id):

    receita = Receita.objects.filter(id=id).first()

    return render(request, 'receita/pages/receita-page.html', context={'receita': receita, 'is_detail': True,
                                                                       })

receitas/templates/receita/pages/categoria.html
{% extends 'global/base.html' %}
{% load static %}

    {% block titulo %}
    {{ titulo }} -  
    {% endblock titulo %}

{% block content %}
    <div class="main-content main-content-list container">
        {% for receita in receitas %}
            {% include 'receita/partes/receita-card.html' %}
        {% endfor %}
    </div>

  
{% endblock content %}

receitas/templates/receita/pages/home.html
{% load static %}
{% include 'receita/partes/head.html' %}

<body>
    <div class="main-header-container">
        <div class="main-header container">
            <h1>
                <a class="link-logo" href="/"> 
                    <i class="logo-icon fa-solid fa-blender"></i>
                    <span> CookBook </span>
                </a>
            </h1>
        </div>
    </div>
</body>
</html>

receitas/templates/receita/pages/receita-page.html
{% extends 'global/base.html' %}

{% block content %}
<div class="main-content main-content-detail container">
    {% include 'receita/partes/receita-card.html' %}
</div>
{% endblock content %}

receitas/templates/receita/partes/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="/" target="_blank" > BECKER'S³</a>
    </div>

    <div class="powered">
        <a href="/" target="_blank" > Python | Django</a>
    </div>
</footer>

receitas/templates/receita/partes/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;900&family=Roboto+Slab:wght@900&display=swap"
    rel="stylesheet">
<script src="https://kit.fontawesome.com/cf3f72cfdd.js"></script>
<link rel="stylesheet" href="{% static 'receita/css/styles.css' %}">

receitas/templates/receita/partes/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="link-logo" href=" {% url 'receita:home' %} "> 
                <i class="logo-icon fa-solid fa-blender"></i>
                <span> CookBook </span>
            </a>
        </h1>
    </div>
</header>

receitas/templates/receita/partes/receita-card.html
<div class=" receita receita-list-item">
    <div class="receita-cover">
        <a href=" {% url 'receita:detalhe' receita.id %} ">
            <img src={{receita.cover.url}} alt="Temporário">
        </a>
    </div>
    <div class="receita-title-contaier">
        <a href=" {% url 'receita:detalhe' receita.id %} ">
            <h2 class="receita-title">
                {{receita.titulo}}
            </h2>
        </a>
    </div>

    <div class="receita-autor">
        {% if receita.usuario is not None %}
            <span class="receita-autor-item">
                <i class="fa-solid fa-clipboard-user"></i>
                {% if receita.usuario.first_name %}
                {{receita.usuario.first_name}} {{receita.usuario.last_name}}
                {% else %}
                {{receita.usuario.username}}
                {% endif %}
            </span>
        {% else %}
            
        {% endif %}
        <span class="receita-autor-item">
            <i class="fa-solid fa-calendar-days"></i>
            {{receita.criacao | date:'d/m/Y' }}
        </span>
            

        {% if receita.categoria is not None %}
            <span class="receita-autor-item">
                <a href={% url 'receita:categoria' receita.categoria.id %} >
                    <i class="fa-solid fa-receipt"></i>
                    <span>{{receita.categoria.name}}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="receita-content">
        <p>{{receita.descricao}}</p>
    </div>

    <div class="receita-meta-container">
        <div class="receita-meta receita-preparacao">
            <h3 class="receita-meta-title"><i class="fa-solid fa-clock-rotate-left"></i> Preparo</h3>
            <div class="receita-meta-text">
                {{receita.tempo_prep}} {{receita.unidade_tempo}}
            </div>
        </div>
        <div class="receita-meta receita-servem">
            <h3 class="receita-meta-title"><i class="fa-solid fa-pizza-slice"></i> Porção</h3>
            <div class="receita-meta-text">
                {{receita.porcoes}} {{receita.unidade_porcao}}
            </div>
        </div>
    </div>

    {% if not is_detail %}
    <footer class="receita-fotter">
        <a href=" {% url 'receita:detalhe' receita.id %} " class="receita read-more button button-dark button-full-width">
            <i class="fa-solid fa-eye"></i>
            <span>Ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail is True %}
        <div class="como-fazer">
            {{receita.modo_preparo|linebreaksbr }}
        </div>
    {% endif %}
</div>

receitas/templates/receita/partes/search.html
<div class="seacher-container">
    <div class="container">
        <form class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="btn-search">
                <i class="fa-solid fa-magnifying-glass"></i>
            </button>
        </form>
    </div>
</div>